### ISSUE TITLE
[Question] Testing the module

### ISSUE THREAD

**Issue by felipemeriga** [kazhala/InquirerPy#12]
Hello, InquirerPy uses prompt_toolkit in the background, which is a library where you are capable of mocking prompt answers. I know that there are some unit tests on that repo, but, is there a way to test and mock a result for InquirerPy prompt function ?

Thanks a lot!

**Comment by kazhala** [comment]
Hi @felipemeriga ,

Depending on how far deep you wanna go with mocking, but if you are just looking to mock the prompt function (which I recommend, there's not really any benefit for you to mock deeper since it has already been tested by the unit test) it would be quite simple.

Module/somefunction.py
```python
from InquirerPy.resolver import prompt

def get_name():
    return prompt({"type": "input", "message": "Name:"})
```

tests/test_somefunction.py
```python
import unittest
from unittest.mock import call, patch

from Module.somefunction import get_name

class TestPrompt(unittest.TestCase):
    @patch("Module.somefunction.prompt")
    def test_get_name(self, mocked_prompt):
        mocked_prompt.return_value = "hello"
        result = get_name()
        self.assertEqual(result, "hello")
```

Might have typo but the idea is just directly mock the prompt function. There's no other consideration on the terminal environment, IO stuff or prompt_toolkit, because these stuff are called later in the prompt function and by mocking it, those will never run.

Lemme know if you need any further assistance (e.g. pytest).

Thanks,
Kevin
