### ISSUE TITLE
[Feature Request] Defaults for multi-select list

### ISSUE THREAD

**Issue by rthill91** [kazhala/InquirerPy#2]
I'd really like to be able to have default selections for a multi-select list. I would envision this as either an extension of the existing `default` key where I could pass a list of selections, or as an option in the choices like

```python
"choices": [
  {"name" "Foo", "value": "foo", "selected": True},
  {"name" "Bar", "value": "bar", "selected": True},
]
```

Apologies if this is already possible and I just missed it.

**Comment by kazhala** [comment]
Hi @rthill91,

You are right, the behaviour you are describing is not present in the current version.

I'll work on this behaviour, it should be a very easy twist.

Thanks,
Kevin

**Comment by kazhala** [comment]
Hi @rthill91,

The new release v0.2.0 has the behaviour implemented. It requires `multiselect=True` and the key name is `enabled`, the reason is to keep it consistent with the checkbox prompt.

```
"choices": [
  {"name" "Foo", "value": "foo", "enabled": True},
  {"name" "Bar", "value": "bar", "enabled": True},
]
```


I'll close the issue for now. If you encounter any issues while using it, feel free to reopen it.

Thanks,
Kevin
